motorcycles=['honda','yamaha','suzuki']
removedmotorcycles=[]
print(motorcycles)
a1=motorcycles.pop()
removedmotorcycles.append(a1)
print(motorcycles)
print(a1)
a2=motorcycles.pop()
removedmotorcycles.append(a2)
print(motorcycles)
print(a2)