firstname="taha";
lastname="imtiaz";
age=21;
fullname=firstname+" "+lastname;
print(firstname);
print(lastname);
print(fullname);
print(firstname,lastname);
fullname1=firstname +" "+lastname +" " +str(age);
print(fullname1);